# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://pmd.github.io
baseurl:
title: PMD
email: pmd-devel@lists.sourceforge.net
author: PMD
description: PMD is a source code analyzer. It finds unused variables, empty catch blocks, unnecessary object creation, and so forth.
keywords: PMD,Java,Salesforce.com Apex,Code Analyzer,Clean Code,Software Development
copyright: 'Copyright &copy; 2017 PMD. All Rights Reserved.'
credits: 'Credits: <a href="https://github.com/swcool/landing-page-theme">Landing Page Theme</a>, based on free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

exclude:
    - .gitignore
    - README.md

# to speed up local builds, exclude the following, too:
#    - 'pmd-5*'
#    - latest

# ----------------------- #
#     PMD vars            #
# ----------------------- #
pmd:
  latestVersion: 6.0.1
  latestVersionDate: 21st January 2018
  downloads:
      - version: 6.0.0
        date: 15th December 2017
      - version: 5.8.1
        date: 1st July 2017
      - version: 5.7.0
        date: 20th May 2017

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: github
    url: https://github.com/pmd/pmd
