# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://pmd.github.io
baseurl:
title: PMD
author: PMD
description: PMD is a source code analyzer. It finds unused variables, empty catch blocks, unnecessary object creation, and so forth.
keywords: PMD,Java,Salesforce.com Apex,Code Analyzer,Clean Code,Software Development
copyright: 'Copyright &copy; 2020 PMD. All Rights Reserved.'
credits: 'Credits: <a href="https://github.com/swcool/landing-page-theme">Landing Page Theme</a>, based on free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

exclude:
    - .gitignore
    - README.md
    - vendor

# Exclude "pmd-*" and "latest" directories
# The docs will be hosted on docs.pmd-code.org
    - 'pmd-*'
    - latest

# ----------------------- #
#     PMD vars            #
# ----------------------- #
pmd:
  latestVersion: 6.24.0
  latestVersionDate: 24-May-2020
  downloads:
      - version: 6.23.0
        date: 24-April-2020
      - version: 6.22.0
        date: 12-March-2020
      - version: 6.21.0
        date: 24-January-2020

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: github
    url: https://github.com/pmd/pmd
