# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://pmd.github.io
baseurl:
title: PMD
email: pmd-devel@lists.sourceforge.net
author: PMD
description: PMD is a source code analyzer. It finds unused variables, empty catch blocks, unnecessary object creation, and so forth.
keywords: PMD,Java,Salesforce.com Apex,Code Analyzer,Clean Code,Software Development
copyright: 'Copyright &copy; 2019 PMD. All Rights Reserved.'
credits: 'Credits: <a href="https://github.com/swcool/landing-page-theme">Landing Page Theme</a>, based on free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

exclude:
    - .gitignore
    - README.md
    - vendor

# to speed up local builds, exclude the following, too:
#    - 'pmd-5*'
#    - 'pmd-6*'

# ----------------------- #
#     PMD vars            #
# ----------------------- #
pmd:
  latestVersion: 6.19.0
  latestVersionDate: 31-October-2019
  downloads:
      - version: 6.18.0
        date: 15-September-2019
      - version: 6.17.0
        date: 28-July-2019
      - version: 6.16.0
        date: 30-June-2019

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: github
    url: https://github.com/pmd/pmd
